import { describe, it, expect } from 'vitest';

/**
 * Phase 8 Unit Tests: User Feedback & Reporting System
 *
 * These tests verify:
 * - Feedback types and structures
 * - Export report generation
 * - Correction calculations
 */

import { FeedbackType, RiskLevel, UserFeedback, UserCorrection } from '@/types';

// ============================================================================
// Local implementations for testing (avoid browser extension imports)
// ============================================================================

function generateExportReport(
  url: string,
  domain: string,
  riskLevel: string,
  threats: string[],
  explanation: string,
  timestamp: number
): string {
  const date = new Date(timestamp).toISOString();
  
  return `SurfSafe Threat Report
========================
Generated: ${date}

URL: ${url}
Domain: ${domain}

Risk Level: ${riskLevel}
${threats.length > 0 ? `\nDetected Threats:\n${threats.map(t => `  • ${t}`).join('\n')}` : '\nNo threats detected.'}

Analysis:
${explanation}

========================
Report generated by SurfSafe Browser Extension
`;
}

function generateJsonExport(
  url: string,
  domain: string,
  riskLevel: string,
  threats: string[],
  explanation: string,
  timestamp: number
): string {
  return JSON.stringify({
    reportVersion: '1.0',
    generatedAt: new Date(timestamp).toISOString(),
    url,
    domain,
    riskLevel,
    threats,
    explanation,
    generatedBy: 'SurfSafe Browser Extension',
  }, null, 2);
}

// ============================================================================
// Feedback Types Tests
// ============================================================================

describe('Feedback Types', () => {
  it('should have correct feedback type values', () => {
    expect(FeedbackType.FALSE_POSITIVE).toBe('FALSE_POSITIVE');
    expect(FeedbackType.FALSE_NEGATIVE).toBe('FALSE_NEGATIVE');
    expect(FeedbackType.ACCURATE).toBe('ACCURATE');
  });

  it('should create valid UserFeedback structure', () => {
    const feedback: UserFeedback = {
      id: 'test-id-123',
      url: 'https://example.com/page',
      domain: 'example.com',
      feedbackType: FeedbackType.FALSE_POSITIVE,
      originalRiskLevel: RiskLevel.HIGH,
      userComment: 'This site is actually safe',
      timestamp: Date.now(),
    };

    expect(feedback.id).toBeDefined();
    expect(feedback.url).toContain('example.com');
    expect(feedback.feedbackType).toBe(FeedbackType.FALSE_POSITIVE);
  });

  it('should create valid UserCorrection structure', () => {
    const correction: UserCorrection = {
      domain: 'example.com',
      adjustment: -0.2,
      feedbackCount: 1,
      lastUpdated: Date.now(),
    };

    expect(correction.adjustment).toBeGreaterThanOrEqual(-1);
    expect(correction.adjustment).toBeLessThanOrEqual(1);
  });
});

// ============================================================================
// Correction Calculation Tests
// ============================================================================

describe('Correction Calculations', () => {
  it('should calculate adjustment for false positive', () => {
    const delta = -0.2; // False positive makes site safer
    expect(delta).toBeLessThan(0);
  });

  it('should calculate adjustment for false negative', () => {
    const delta = 0.2; // False negative makes site riskier
    expect(delta).toBeGreaterThan(0);
  });

  it('should calculate adjustment for accurate', () => {
    const delta = 0; // Accurate = no change
    expect(delta).toBe(0);
  });

  it('should calculate average adjustment correctly', () => {
    // Simulate averaging adjustments
    const existingAdjustment = -0.2;
    const existingCount = 1;
    const newDelta = 0.2;

    const newAdjustment = (existingAdjustment * existingCount + newDelta) / (existingCount + 1);
    expect(newAdjustment).toBe(0); // (-0.2 + 0.2) / 2 = 0
  });

  it('should cap adjustment at boundaries', () => {
    const highAdjustment = 1.5;
    const capped = Math.max(-1, Math.min(1, highAdjustment));
    expect(capped).toBe(1);

    const lowAdjustment = -1.5;
    const cappedLow = Math.max(-1, Math.min(1, lowAdjustment));
    expect(cappedLow).toBe(-1);
  });
});

// ============================================================================
// Export Report Tests
// ============================================================================

describe('Export Report Generation', () => {
  const testUrl = 'https://example.com/test-page';
  const testDomain = 'example.com';
  const testTimestamp = Date.now();

  describe('Text Report', () => {
    it('should generate report with all fields', () => {
      const report = generateExportReport(
        testUrl,
        testDomain,
        RiskLevel.MEDIUM,
        ['URGENCY', 'PRESSURE'],
        'This page contains pressure tactics.',
        testTimestamp
      );

      expect(report).toContain('SurfSafe Threat Report');
      expect(report).toContain(testUrl);
      expect(report).toContain(testDomain);
      expect(report).toContain('MEDIUM');
      expect(report).toContain('URGENCY');
      expect(report).toContain('PRESSURE');
      expect(report).toContain('pressure tactics');
    });

    it('should handle empty threats array', () => {
      const report = generateExportReport(
        testUrl,
        testDomain,
        RiskLevel.SAFE,
        [],
        'No issues found.',
        testTimestamp
      );

      expect(report).toContain('No threats detected');
    });

    it('should format threats as bullet points', () => {
      const report = generateExportReport(
        testUrl,
        testDomain,
        RiskLevel.HIGH,
        ['URGENCY', 'TOO_GOOD'],
        'Multiple issues.',
        testTimestamp
      );

      expect(report).toContain('• URGENCY');
      expect(report).toContain('• TOO_GOOD');
    });
  });

  describe('JSON Report', () => {
    it('should generate valid JSON', () => {
      const report = generateJsonExport(
        testUrl,
        testDomain,
        RiskLevel.LOW,
        ['SUSPICIOUS_LINK'],
        'Minor concern.',
        testTimestamp
      );

      expect(() => JSON.parse(report)).not.toThrow();
    });

    it('should include all required fields', () => {
      const report = generateJsonExport(
        testUrl,
        testDomain,
        RiskLevel.HIGH,
        ['IMPERSONATION'],
        'High risk detected.',
        testTimestamp
      );

      const parsed = JSON.parse(report);
      expect(parsed.reportVersion).toBe('1.0');
      expect(parsed.url).toBe(testUrl);
      expect(parsed.domain).toBe(testDomain);
      expect(parsed.riskLevel).toBe(RiskLevel.HIGH);
      expect(parsed.threats).toContain('IMPERSONATION');
      expect(parsed.generatedBy).toBe('SurfSafe Browser Extension');
    });

    it('should format with proper indentation', () => {
      const report = generateJsonExport(
        testUrl,
        testDomain,
        RiskLevel.SAFE,
        [],
        'Clean.',
        testTimestamp
      );

      // Pretty printed JSON should have newlines
      expect(report).toContain('\n');
    });
  });
});

// ============================================================================
// Feedback Flow Tests
// ============================================================================

describe('Feedback Flow', () => {
  it('should create feedback ID with UUID format', () => {
    const id = crypto.randomUUID();
    expect(id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
  });

  it('should normalize domain correctly', () => {
    const domain = 'www.Example.COM';
    const normalized = domain.toLowerCase().replace(/^www\./, '');
    expect(normalized).toBe('example.com');
  });

  it('should keep feedback history limited', () => {
    const maxFeedback = 100;
    const existing = Array(105).fill({});
    const trimmed = existing.slice(-maxFeedback);
    expect(trimmed.length).toBe(100);
  });
});
